package com.gzhz.kcmqmonitor.entity;

import java.util.Date;

public class DynMemberStaff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.staffId
     *
     * @mbggenerated
     */
    private Long staffid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.staffNo
     *
     * @mbggenerated
     */
    private Long staffno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.staffName
     *
     * @mbggenerated
     */
    private String staffname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.mobile2
     *
     * @mbggenerated
     */
    private String mobile2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.officePhone
     *
     * @mbggenerated
     */
    private String officephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.safetyQuestion
     *
     * @mbggenerated
     */
    private String safetyquestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.questionResult
     *
     * @mbggenerated
     */
    private String questionresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.birthDay
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.homepage
     *
     * @mbggenerated
     */
    private String homepage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.rowId
     *
     * @mbggenerated
     */
    private String rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.msn
     *
     * @mbggenerated
     */
    private String msn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.registerDate
     *
     * @mbggenerated
     */
    private Date registerdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.pastTime
     *
     * @mbggenerated
     */
    private Date pasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.identifying
     *
     * @mbggenerated
     */
    private String identifying;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.headImageUrl
     *
     * @mbggenerated
     */
    private String headimageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.smsState
     *
     * @mbggenerated
     */
    private Byte smsstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.secretary
     *
     * @mbggenerated
     */
    private String secretary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.isEnable
     *
     * @mbggenerated
     */
    private Boolean isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.isDelete
     *
     * @mbggenerated
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.a8id
     *
     * @mbggenerated
     */
    private Long a8id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.a8departmentId
     *
     * @mbggenerated
     */
    private Long a8departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.a8LoginId
     *
     * @mbggenerated
     */
    private String a8loginid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.a8sortid
     *
     * @mbggenerated
     */
    private Integer a8sortid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.a8orgid
     *
     * @mbggenerated
     */
    private Long a8orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.a8PostId
     *
     * @mbggenerated
     */
    private Long a8postid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.a8LevelId
     *
     * @mbggenerated
     */
    private Long a8levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.OTHERID
     *
     * @mbggenerated
     */
    private Long otherid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dyn_member_staff.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.staffId
     *
     * @return the value of dyn_member_staff.staffId
     *
     * @mbggenerated
     */
    public Long getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.staffId
     *
     * @param staffid the value for dyn_member_staff.staffId
     *
     * @mbggenerated
     */
    public void setStaffid(Long staffid) {
        this.staffid = staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.staffNo
     *
     * @return the value of dyn_member_staff.staffNo
     *
     * @mbggenerated
     */
    public Long getStaffno() {
        return staffno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.staffNo
     *
     * @param staffno the value for dyn_member_staff.staffNo
     *
     * @mbggenerated
     */
    public void setStaffno(Long staffno) {
        this.staffno = staffno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.guid
     *
     * @return the value of dyn_member_staff.guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.guid
     *
     * @param guid the value for dyn_member_staff.guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.username
     *
     * @return the value of dyn_member_staff.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.username
     *
     * @param username the value for dyn_member_staff.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.staffName
     *
     * @return the value of dyn_member_staff.staffName
     *
     * @mbggenerated
     */
    public String getStaffname() {
        return staffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.staffName
     *
     * @param staffname the value for dyn_member_staff.staffName
     *
     * @mbggenerated
     */
    public void setStaffname(String staffname) {
        this.staffname = staffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.password
     *
     * @return the value of dyn_member_staff.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.password
     *
     * @param password the value for dyn_member_staff.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.email
     *
     * @return the value of dyn_member_staff.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.email
     *
     * @param email the value for dyn_member_staff.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.mobile
     *
     * @return the value of dyn_member_staff.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.mobile
     *
     * @param mobile the value for dyn_member_staff.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.mobile2
     *
     * @return the value of dyn_member_staff.mobile2
     *
     * @mbggenerated
     */
    public String getMobile2() {
        return mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.mobile2
     *
     * @param mobile2 the value for dyn_member_staff.mobile2
     *
     * @mbggenerated
     */
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.officePhone
     *
     * @return the value of dyn_member_staff.officePhone
     *
     * @mbggenerated
     */
    public String getOfficephone() {
        return officephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.officePhone
     *
     * @param officephone the value for dyn_member_staff.officePhone
     *
     * @mbggenerated
     */
    public void setOfficephone(String officephone) {
        this.officephone = officephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.safetyQuestion
     *
     * @return the value of dyn_member_staff.safetyQuestion
     *
     * @mbggenerated
     */
    public String getSafetyquestion() {
        return safetyquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.safetyQuestion
     *
     * @param safetyquestion the value for dyn_member_staff.safetyQuestion
     *
     * @mbggenerated
     */
    public void setSafetyquestion(String safetyquestion) {
        this.safetyquestion = safetyquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.questionResult
     *
     * @return the value of dyn_member_staff.questionResult
     *
     * @mbggenerated
     */
    public String getQuestionresult() {
        return questionresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.questionResult
     *
     * @param questionresult the value for dyn_member_staff.questionResult
     *
     * @mbggenerated
     */
    public void setQuestionresult(String questionresult) {
        this.questionresult = questionresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.sex
     *
     * @return the value of dyn_member_staff.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.sex
     *
     * @param sex the value for dyn_member_staff.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.birthDay
     *
     * @return the value of dyn_member_staff.birthDay
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.birthDay
     *
     * @param birthday the value for dyn_member_staff.birthDay
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.homepage
     *
     * @return the value of dyn_member_staff.homepage
     *
     * @mbggenerated
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.homepage
     *
     * @param homepage the value for dyn_member_staff.homepage
     *
     * @mbggenerated
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.qq
     *
     * @return the value of dyn_member_staff.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.qq
     *
     * @param qq the value for dyn_member_staff.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.rowId
     *
     * @return the value of dyn_member_staff.rowId
     *
     * @mbggenerated
     */
    public String getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.rowId
     *
     * @param rowid the value for dyn_member_staff.rowId
     *
     * @mbggenerated
     */
    public void setRowid(String rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.msn
     *
     * @return the value of dyn_member_staff.msn
     *
     * @mbggenerated
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.msn
     *
     * @param msn the value for dyn_member_staff.msn
     *
     * @mbggenerated
     */
    public void setMsn(String msn) {
        this.msn = msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.registerDate
     *
     * @return the value of dyn_member_staff.registerDate
     *
     * @mbggenerated
     */
    public Date getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.registerDate
     *
     * @param registerdate the value for dyn_member_staff.registerDate
     *
     * @mbggenerated
     */
    public void setRegisterdate(Date registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.pastTime
     *
     * @return the value of dyn_member_staff.pastTime
     *
     * @mbggenerated
     */
    public Date getPasttime() {
        return pasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.pastTime
     *
     * @param pasttime the value for dyn_member_staff.pastTime
     *
     * @mbggenerated
     */
    public void setPasttime(Date pasttime) {
        this.pasttime = pasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.identifying
     *
     * @return the value of dyn_member_staff.identifying
     *
     * @mbggenerated
     */
    public String getIdentifying() {
        return identifying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.identifying
     *
     * @param identifying the value for dyn_member_staff.identifying
     *
     * @mbggenerated
     */
    public void setIdentifying(String identifying) {
        this.identifying = identifying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.headImageUrl
     *
     * @return the value of dyn_member_staff.headImageUrl
     *
     * @mbggenerated
     */
    public String getHeadimageurl() {
        return headimageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.headImageUrl
     *
     * @param headimageurl the value for dyn_member_staff.headImageUrl
     *
     * @mbggenerated
     */
    public void setHeadimageurl(String headimageurl) {
        this.headimageurl = headimageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.smsState
     *
     * @return the value of dyn_member_staff.smsState
     *
     * @mbggenerated
     */
    public Byte getSmsstate() {
        return smsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.smsState
     *
     * @param smsstate the value for dyn_member_staff.smsState
     *
     * @mbggenerated
     */
    public void setSmsstate(Byte smsstate) {
        this.smsstate = smsstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.sort
     *
     * @return the value of dyn_member_staff.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.sort
     *
     * @param sort the value for dyn_member_staff.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.secretary
     *
     * @return the value of dyn_member_staff.secretary
     *
     * @mbggenerated
     */
    public String getSecretary() {
        return secretary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.secretary
     *
     * @param secretary the value for dyn_member_staff.secretary
     *
     * @mbggenerated
     */
    public void setSecretary(String secretary) {
        this.secretary = secretary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.isEnable
     *
     * @return the value of dyn_member_staff.isEnable
     *
     * @mbggenerated
     */
    public Boolean getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.isEnable
     *
     * @param isenable the value for dyn_member_staff.isEnable
     *
     * @mbggenerated
     */
    public void setIsenable(Boolean isenable) {
        this.isenable = isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.isDelete
     *
     * @return the value of dyn_member_staff.isDelete
     *
     * @mbggenerated
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.isDelete
     *
     * @param isdelete the value for dyn_member_staff.isDelete
     *
     * @mbggenerated
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.updateTime
     *
     * @return the value of dyn_member_staff.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.updateTime
     *
     * @param updatetime the value for dyn_member_staff.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.a8id
     *
     * @return the value of dyn_member_staff.a8id
     *
     * @mbggenerated
     */
    public Long getA8id() {
        return a8id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.a8id
     *
     * @param a8id the value for dyn_member_staff.a8id
     *
     * @mbggenerated
     */
    public void setA8id(Long a8id) {
        this.a8id = a8id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.a8departmentId
     *
     * @return the value of dyn_member_staff.a8departmentId
     *
     * @mbggenerated
     */
    public Long getA8departmentid() {
        return a8departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.a8departmentId
     *
     * @param a8departmentid the value for dyn_member_staff.a8departmentId
     *
     * @mbggenerated
     */
    public void setA8departmentid(Long a8departmentid) {
        this.a8departmentid = a8departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.a8LoginId
     *
     * @return the value of dyn_member_staff.a8LoginId
     *
     * @mbggenerated
     */
    public String getA8loginid() {
        return a8loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.a8LoginId
     *
     * @param a8loginid the value for dyn_member_staff.a8LoginId
     *
     * @mbggenerated
     */
    public void setA8loginid(String a8loginid) {
        this.a8loginid = a8loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.a8sortid
     *
     * @return the value of dyn_member_staff.a8sortid
     *
     * @mbggenerated
     */
    public Integer getA8sortid() {
        return a8sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.a8sortid
     *
     * @param a8sortid the value for dyn_member_staff.a8sortid
     *
     * @mbggenerated
     */
    public void setA8sortid(Integer a8sortid) {
        this.a8sortid = a8sortid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.a8orgid
     *
     * @return the value of dyn_member_staff.a8orgid
     *
     * @mbggenerated
     */
    public Long getA8orgid() {
        return a8orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.a8orgid
     *
     * @param a8orgid the value for dyn_member_staff.a8orgid
     *
     * @mbggenerated
     */
    public void setA8orgid(Long a8orgid) {
        this.a8orgid = a8orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.a8PostId
     *
     * @return the value of dyn_member_staff.a8PostId
     *
     * @mbggenerated
     */
    public Long getA8postid() {
        return a8postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.a8PostId
     *
     * @param a8postid the value for dyn_member_staff.a8PostId
     *
     * @mbggenerated
     */
    public void setA8postid(Long a8postid) {
        this.a8postid = a8postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.a8LevelId
     *
     * @return the value of dyn_member_staff.a8LevelId
     *
     * @mbggenerated
     */
    public Long getA8levelid() {
        return a8levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.a8LevelId
     *
     * @param a8levelid the value for dyn_member_staff.a8LevelId
     *
     * @mbggenerated
     */
    public void setA8levelid(Long a8levelid) {
        this.a8levelid = a8levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.OTHERID
     *
     * @return the value of dyn_member_staff.OTHERID
     *
     * @mbggenerated
     */
    public Long getOtherid() {
        return otherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.OTHERID
     *
     * @param otherid the value for dyn_member_staff.OTHERID
     *
     * @mbggenerated
     */
    public void setOtherid(Long otherid) {
        this.otherid = otherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dyn_member_staff.description
     *
     * @return the value of dyn_member_staff.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dyn_member_staff.description
     *
     * @param description the value for dyn_member_staff.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}