package com.gzhz.kcmqmonitor.entity;

public class KcAttList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.guid
     *
     * @mbggenerated
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.sessionId
     *
     * @mbggenerated
     */
    private String sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.atturl
     *
     * @mbggenerated
     */
    private String atturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.addUser
     *
     * @mbggenerated
     */
    private Long adduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.addTime
     *
     * @mbggenerated
     */
    private Integer addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.sort
     *
     * @mbggenerated
     */
    private Byte sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.resource
     *
     * @mbggenerated
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.filename
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.lastEditUser
     *
     * @mbggenerated
     */
    private Long lastedituser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.lastEditTime
     *
     * @mbggenerated
     */
    private Integer lastedittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_att_list.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.id
     *
     * @return the value of kc_att_list.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.id
     *
     * @param id the value for kc_att_list.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.guid
     *
     * @return the value of kc_att_list.guid
     *
     * @mbggenerated
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.guid
     *
     * @param guid the value for kc_att_list.guid
     *
     * @mbggenerated
     */
    public void setGuid(String guid) {
        this.guid = guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.sessionId
     *
     * @return the value of kc_att_list.sessionId
     *
     * @mbggenerated
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.sessionId
     *
     * @param sessionid the value for kc_att_list.sessionId
     *
     * @mbggenerated
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.atturl
     *
     * @return the value of kc_att_list.atturl
     *
     * @mbggenerated
     */
    public String getAtturl() {
        return atturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.atturl
     *
     * @param atturl the value for kc_att_list.atturl
     *
     * @mbggenerated
     */
    public void setAtturl(String atturl) {
        this.atturl = atturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.title
     *
     * @return the value of kc_att_list.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.title
     *
     * @param title the value for kc_att_list.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.addUser
     *
     * @return the value of kc_att_list.addUser
     *
     * @mbggenerated
     */
    public Long getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.addUser
     *
     * @param adduser the value for kc_att_list.addUser
     *
     * @mbggenerated
     */
    public void setAdduser(Long adduser) {
        this.adduser = adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.addTime
     *
     * @return the value of kc_att_list.addTime
     *
     * @mbggenerated
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.addTime
     *
     * @param addtime the value for kc_att_list.addTime
     *
     * @mbggenerated
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.sort
     *
     * @return the value of kc_att_list.sort
     *
     * @mbggenerated
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.sort
     *
     * @param sort the value for kc_att_list.sort
     *
     * @mbggenerated
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.resource
     *
     * @return the value of kc_att_list.resource
     *
     * @mbggenerated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.resource
     *
     * @param resource the value for kc_att_list.resource
     *
     * @mbggenerated
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.state
     *
     * @return the value of kc_att_list.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.state
     *
     * @param state the value for kc_att_list.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.filename
     *
     * @return the value of kc_att_list.filename
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.filename
     *
     * @param filename the value for kc_att_list.filename
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.lastEditUser
     *
     * @return the value of kc_att_list.lastEditUser
     *
     * @mbggenerated
     */
    public Long getLastedituser() {
        return lastedituser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.lastEditUser
     *
     * @param lastedituser the value for kc_att_list.lastEditUser
     *
     * @mbggenerated
     */
    public void setLastedituser(Long lastedituser) {
        this.lastedituser = lastedituser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.lastEditTime
     *
     * @return the value of kc_att_list.lastEditTime
     *
     * @mbggenerated
     */
    public Integer getLastedittime() {
        return lastedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.lastEditTime
     *
     * @param lastedittime the value for kc_att_list.lastEditTime
     *
     * @mbggenerated
     */
    public void setLastedittime(Integer lastedittime) {
        this.lastedittime = lastedittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_att_list.status
     *
     * @return the value of kc_att_list.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_att_list.status
     *
     * @param status the value for kc_att_list.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}