package com.gzhz.kcmqmonitor.entity;

public class KcFavorites {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_favorites.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_favorites.kid
     *
     * @mbggenerated
     */
    private Integer kid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_favorites.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_favorites.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_favorites.id
     *
     * @return the value of kc_favorites.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_favorites.id
     *
     * @param id the value for kc_favorites.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_favorites.kid
     *
     * @return the value of kc_favorites.kid
     *
     * @mbggenerated
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_favorites.kid
     *
     * @param kid the value for kc_favorites.kid
     *
     * @mbggenerated
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_favorites.uid
     *
     * @return the value of kc_favorites.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_favorites.uid
     *
     * @param uid the value for kc_favorites.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_favorites.state
     *
     * @return the value of kc_favorites.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_favorites.state
     *
     * @param state the value for kc_favorites.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }
}