package com.gzhz.kcmqmonitor.entity;

public class KcInfoBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.docid
     *
     * @mbggenerated
     */
    private Integer docid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.forid
     *
     * @mbggenerated
     */
    private Integer forid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.replyforid
     *
     * @mbggenerated
     */
    private Integer replyforid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.sessionId
     *
     * @mbggenerated
     */
    private String sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.sessionGuid
     *
     * @mbggenerated
     */
    private String sessionguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.infotype
     *
     * @mbggenerated
     */
    private Integer infotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.attguid
     *
     * @mbggenerated
     */
    private String attguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.staffNo
     *
     * @mbggenerated
     */
    private Long staffno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.orgid
     *
     * @mbggenerated
     */
    private Long orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.publishUser
     *
     * @mbggenerated
     */
    private Long publishuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.publishTime
     *
     * @mbggenerated
     */
    private Integer publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.readTime
     *
     * @mbggenerated
     */
    private Integer readtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.readOnly
     *
     * @mbggenerated
     */
    private Integer readonly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.inboxdel
     *
     * @mbggenerated
     */
    private Integer inboxdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.outboxdel
     *
     * @mbggenerated
     */
    private Integer outboxdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.streamState
     *
     * @mbggenerated
     */
    private String streamstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.isSms
     *
     * @mbggenerated
     */
    private Integer issms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kc_info_box.isDelete
     *
     * @mbggenerated
     */
    private Byte isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.id
     *
     * @return the value of kc_info_box.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.id
     *
     * @param id the value for kc_info_box.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.docid
     *
     * @return the value of kc_info_box.docid
     *
     * @mbggenerated
     */
    public Integer getDocid() {
        return docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.docid
     *
     * @param docid the value for kc_info_box.docid
     *
     * @mbggenerated
     */
    public void setDocid(Integer docid) {
        this.docid = docid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.forid
     *
     * @return the value of kc_info_box.forid
     *
     * @mbggenerated
     */
    public Integer getForid() {
        return forid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.forid
     *
     * @param forid the value for kc_info_box.forid
     *
     * @mbggenerated
     */
    public void setForid(Integer forid) {
        this.forid = forid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.replyforid
     *
     * @return the value of kc_info_box.replyforid
     *
     * @mbggenerated
     */
    public Integer getReplyforid() {
        return replyforid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.replyforid
     *
     * @param replyforid the value for kc_info_box.replyforid
     *
     * @mbggenerated
     */
    public void setReplyforid(Integer replyforid) {
        this.replyforid = replyforid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.sessionId
     *
     * @return the value of kc_info_box.sessionId
     *
     * @mbggenerated
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.sessionId
     *
     * @param sessionid the value for kc_info_box.sessionId
     *
     * @mbggenerated
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.sessionGuid
     *
     * @return the value of kc_info_box.sessionGuid
     *
     * @mbggenerated
     */
    public String getSessionguid() {
        return sessionguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.sessionGuid
     *
     * @param sessionguid the value for kc_info_box.sessionGuid
     *
     * @mbggenerated
     */
    public void setSessionguid(String sessionguid) {
        this.sessionguid = sessionguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.type
     *
     * @return the value of kc_info_box.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.type
     *
     * @param type the value for kc_info_box.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.category
     *
     * @return the value of kc_info_box.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.category
     *
     * @param category the value for kc_info_box.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.infotype
     *
     * @return the value of kc_info_box.infotype
     *
     * @mbggenerated
     */
    public Integer getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.infotype
     *
     * @param infotype the value for kc_info_box.infotype
     *
     * @mbggenerated
     */
    public void setInfotype(Integer infotype) {
        this.infotype = infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.attguid
     *
     * @return the value of kc_info_box.attguid
     *
     * @mbggenerated
     */
    public String getAttguid() {
        return attguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.attguid
     *
     * @param attguid the value for kc_info_box.attguid
     *
     * @mbggenerated
     */
    public void setAttguid(String attguid) {
        this.attguid = attguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.title
     *
     * @return the value of kc_info_box.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.title
     *
     * @param title the value for kc_info_box.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.content
     *
     * @return the value of kc_info_box.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.content
     *
     * @param content the value for kc_info_box.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.staffNo
     *
     * @return the value of kc_info_box.staffNo
     *
     * @mbggenerated
     */
    public Long getStaffno() {
        return staffno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.staffNo
     *
     * @param staffno the value for kc_info_box.staffNo
     *
     * @mbggenerated
     */
    public void setStaffno(Long staffno) {
        this.staffno = staffno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.orgid
     *
     * @return the value of kc_info_box.orgid
     *
     * @mbggenerated
     */
    public Long getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.orgid
     *
     * @param orgid the value for kc_info_box.orgid
     *
     * @mbggenerated
     */
    public void setOrgid(Long orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.publishUser
     *
     * @return the value of kc_info_box.publishUser
     *
     * @mbggenerated
     */
    public Long getPublishuser() {
        return publishuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.publishUser
     *
     * @param publishuser the value for kc_info_box.publishUser
     *
     * @mbggenerated
     */
    public void setPublishuser(Long publishuser) {
        this.publishuser = publishuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.publishTime
     *
     * @return the value of kc_info_box.publishTime
     *
     * @mbggenerated
     */
    public Integer getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.publishTime
     *
     * @param publishtime the value for kc_info_box.publishTime
     *
     * @mbggenerated
     */
    public void setPublishtime(Integer publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.readTime
     *
     * @return the value of kc_info_box.readTime
     *
     * @mbggenerated
     */
    public Integer getReadtime() {
        return readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.readTime
     *
     * @param readtime the value for kc_info_box.readTime
     *
     * @mbggenerated
     */
    public void setReadtime(Integer readtime) {
        this.readtime = readtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.readOnly
     *
     * @return the value of kc_info_box.readOnly
     *
     * @mbggenerated
     */
    public Integer getReadonly() {
        return readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.readOnly
     *
     * @param readonly the value for kc_info_box.readOnly
     *
     * @mbggenerated
     */
    public void setReadonly(Integer readonly) {
        this.readonly = readonly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.inboxdel
     *
     * @return the value of kc_info_box.inboxdel
     *
     * @mbggenerated
     */
    public Integer getInboxdel() {
        return inboxdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.inboxdel
     *
     * @param inboxdel the value for kc_info_box.inboxdel
     *
     * @mbggenerated
     */
    public void setInboxdel(Integer inboxdel) {
        this.inboxdel = inboxdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.outboxdel
     *
     * @return the value of kc_info_box.outboxdel
     *
     * @mbggenerated
     */
    public Integer getOutboxdel() {
        return outboxdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.outboxdel
     *
     * @param outboxdel the value for kc_info_box.outboxdel
     *
     * @mbggenerated
     */
    public void setOutboxdel(Integer outboxdel) {
        this.outboxdel = outboxdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.state
     *
     * @return the value of kc_info_box.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.state
     *
     * @param state the value for kc_info_box.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.streamState
     *
     * @return the value of kc_info_box.streamState
     *
     * @mbggenerated
     */
    public String getStreamstate() {
        return streamstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.streamState
     *
     * @param streamstate the value for kc_info_box.streamState
     *
     * @mbggenerated
     */
    public void setStreamstate(String streamstate) {
        this.streamstate = streamstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.isSms
     *
     * @return the value of kc_info_box.isSms
     *
     * @mbggenerated
     */
    public Integer getIssms() {
        return issms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.isSms
     *
     * @param issms the value for kc_info_box.isSms
     *
     * @mbggenerated
     */
    public void setIssms(Integer issms) {
        this.issms = issms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kc_info_box.sort
     *
     * @return the value of kc_info_box.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kc_info_box.sort
     *
     * @param sort the value for kc_info_box.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Byte getIsdelete() {
        return isdelete;
    }

    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }
}